export const environment = {
  production: true,
  subtitle: `Afterwork Sopra Steria 23 Juin 2022`,
  teamNamesAutocomplete: [
    "ALS",
    "CCH",
    "DP",
    "Edition (Intro)",
    "Edition GF",
    "Edition GL",
    "Ingénierie de développement",
    "Management",
    "PO",
    "PS CTECH",
    "PS GL",
    "PS GF",
    "PS MIG",
    "PS SCO",
    "QNR",
    "RC",
    "SM GF",
    "SM TT",
  ],
  favicon: `favicon-sopra.ico`
};
